### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: __classPrivateFieldGet(...).connect is not a function

### ISSUE THREAD

**Issue by nshusr** [node-casbin/prisma-adapter#19]
use package throw UnhandledPromiseRejectionWarning: TypeError: __classPrivateFieldGet(...).connect is not a function

```
> ts-node -r tsconfig-paths/register ./src/test.ts
(node:62592) UnhandledPromiseRejectionWarning: TypeError: __classPrivateFieldGet(...).connect is not a function
    at PrismaAdapter.<anonymous> (/Users/mac/code/node_modules/.pnpm/casbin-prisma-adapter@1.0.1_201a74a737cba3a1c6167bc5300313ec/node_modules/casbin-prisma-adapter/lib/adapter.js:35:57)
    at Generator.next (<anonymous>)
    at /Users/mac/code/node_modules/.pnpm/casbin-prisma-adapter@1.0.1_201a74a737cba3a1c6167bc5300313ec/node_modules/casbin-prisma-adapter/lib/adapter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mac/code/node_modules/.pnpm/casbin-prisma-adapter@1.0.1_201a74a737cba3a1c6167bc5300313ec/node_modules/casbin-prisma-adapter/lib/adapter.js:4:12)
    at PrismaAdapter.<anonymous> (/Users/mac/code/node_modules/.pnpm/casbin-prisma-adapter@1.0.1_201a74a737cba3a1c6167bc5300313ec/node_modules/casbin-prisma-adapter/lib/adapter.js:33:31)
    at Function.<anonymous> (/Users/mac/code/node_modules/.pnpm/casbin-prisma-adapter@1.0.1_201a74a737cba3a1c6167bc5300313ec/node_modules/casbin-prisma-adapter/lib/adapter.js:175:52)
    at Generator.next (<anonymous>)
    at /Users/mac/code/node_modules/.pnpm/casbin-prisma-adapter@1.0.1_201a74a737cba3a1c6167bc5300313ec/node_modules/casbin-prisma-adapter/lib/adapter.js:8:71
    at new Promise (<anonymous>)
```

env
"typescript": "^4.2.4",
"casbin": "^5.6.1",
"casbin-prisma-adapter": "^1.0.1",
"@prisma/client": "^2.20.1",
"prisma": "^2.20.1",

**Comment by hsluoyz** [comment]
@nodece @zhmushan can you move the package: https://www.npmjs.com/package/casbin-prisma-adapter to the `casbin` org: https://www.npmjs.com/settings/casbin/packages ?

**Comment by nshusr** [comment]
@hsluoyz I do not have permission “Cannot read property 'role' of null”
